### ISSUE TITLE
can not import gym_minigrid.wrappers.FullyObsOneHotWrapper

### ISSUE THREAD

**Issue by THBUer-yw** [rohitrango/BC-regularized-GAIL#1]
I would like to run  experiments for the mini-grid environments but got the following errors:

**AttributeError: module 'gym_minigrid.wrappers' has no attribute 'FullyObsOneHotWrapper'**

And then I checked different versions for the gym_minigrid packages. None of them contains the class of FullyObsOneHotWrapper.

Does anyone know how to correctly run the code for mini-grid tasks?

**Comment by rohitrango** [comment]
Please use this fork of the gym-minigrid repo: https://github.com/rohitrango/gym-minigrid
