### ISSUE TITLE
predict reward 

### ISSUE THREAD

**Issue by xubo92** [rohitrango/BC-regularized-GAIL#4]
Hi @rohitrango 

I'm here again and thanks for your previous answers!

In function `predict_reward`, I was wondering why we need to use `reward = - (1 - s).log()` rather than the original form from GAIL paper `reward = s.log()`. Is there any special reasons?

Thanks!

**Comment by rohitrango** [comment]
Choice of reward functions have effect on training dynamics https://arxiv.org/pdf/2009.09467.pdf
